# Shared verifier for the counterexample scripts in this directory.
#
# VerifySaxlCounterexample(gens, dim, expOrder, expHoles) checks that the
# group H generated by the given matrices in GL(dim, 3) satisfies:
#
#   - |H| = expOrder, and H acts irreducibly on V = GF(3)^dim;
#   - H has exactly one regular orbit R on V (so |R| = |H|);
#   - exactly expHoles vectors of V lie outside R + R, and every one of
#     them lies in R + R + R.
#
# Since R, R + R and R + R + R are H-invariant, it suffices to classify
# one representative of every H-orbit on V; the orbits are enumerated by
# a breadth-first sweep.  By the sumset criterion, the conclusion is that
# the Saxl graph of the primitive affine group V:H has diameter exactly 3
# and that its expHoles vectors outside R + R witness pairs of vertices
# with no common neighbour.

Require := function(condition, message)
  if not condition then
    Error(message);
  fi;
end;;

# A monomial matrix over GF(3): coordinate i is sent to coordinate
# images[i] (0-based, as in the stored generator data) with sign
# signs[i], where 1 means 1 and 2 means -1.
MonomialGen := function(dim, images, signs)
  local F, M, i;
  F := GF(3);
  M := NullMat(dim, dim, F);
  for i in [1..dim] do
    M[i][images[i] + 1] := signs[i] * One(F);
  od;
  for i in [1..dim] do
    ConvertToVectorRep(M[i], 3);
  od;
  ConvertToMatrixRep(M, 3);
  return M;
end;;

VerifySaxlCounterexample := function(gens, dim, expOrder, expHoles)
  local F, H, q, num, expo, ffe, vfn, tests, k, seen, reps, sizes, Rset,
        v0, queue, head, v, w, kk, g, i, t, in2R, in3R, holes, Rnums;

  F := GF(3);
  H := Group(gens);
  Require(Size(H) = expOrder, "wrong group order");
  Require(MTX.IsIrreducible(GModuleByMats(gens, F)),
          "the group should act irreducibly");
  Print("group of order ", expOrder,
        " constructed, irreducibility verified\n");

  q := 3^dim;
  num := v -> NumberFFVector(v, 3) + 1;

  # the inverse of the numbering, calibrated against NumberFFVector
  expo := [];
  for i in [1..dim] do
    v := ListWithIdenticalEntries(dim, Zero(F));
    v[i] := One(F);
    ConvertToVectorRep(v, 3);
    expo[i] := LogInt(NumberFFVector(v, 3), 3);
  od;
  ffe := [Zero(F), One(F), 2 * One(F)];
  vfn := function(k)
    local digs, vec, j;
    digs := CoefficientsQadic(k - 1, 3);
    vec := [];
    for j in [1..dim] do
      if expo[j] + 1 <= Length(digs) then
        vec[j] := ffe[digs[expo[j] + 1] + 1];
      else
        vec[j] := ffe[1];
      fi;
    od;
    ConvertToVectorRep(vec, 3);
    return vec;
  end;
  tests := Set(List([0..49], t -> 1 + QuoInt(t * (q - 1), 49)));
  for k in tests do
    Require(num(vfn(k)) = k, "numbering self-test failed");
  od;

  # breadth-first orbit sweep
  seen := BlistList([1..q], []);
  reps := [];
  sizes := [];
  Rset := fail;
  for k in [1..q] do
    if not seen[k] then
      seen[k] := true;
      v0 := vfn(k);
      queue := [v0];
      head := 1;
      while head <= Length(queue) do
        v := queue[head];
        head := head + 1;
        for g in gens do
          w := v * g;
          kk := num(w);
          if not seen[kk] then
            seen[kk] := true;
            Add(queue, w);
          fi;
        od;
      od;
      Add(reps, v0);
      Add(sizes, Length(queue));
      if Length(queue) = expOrder then
        Require(Rset = fail, "more than one regular orbit");
        Rset := Set(queue);
      fi;
      queue := [];
    fi;
  od;
  Require(Rset <> fail, "no regular orbit found");
  Print("orbit sweep complete: ", Length(reps),
        " orbits, one regular orbit of size ", expOrder, "\n");

  # classify one representative of every orbit, testing membership in R
  # through a boolean list indexed by vector numbers
  Rnums := BlistList([1..q], List(Rset, num));
  # Since R is one H-orbit and R + R is H-invariant, testing one element
  # suffices to verify R is contained in R + R.
  Require(ForAny(Rset, x -> Rnums[num(Rset[1] - x)]),
          "the regular orbit should lie in R + R");
  holes := 0;
  for i in [1..Length(reps)] do
    t := reps[i];
    if not IsZero(t) and not Rnums[num(t)] then
      in2R := ForAny(Rset, x -> Rnums[num(t - x)]);
      if not in2R then
        in3R := ForAny(Rset,
                  x -> ForAny(Rset, u -> Rnums[num(t - x - u)]));
        Require(in3R, "a vector lies at distance greater than 3");
        holes := holes + sizes[i];
      fi;
    fi;
  od;
  Require(holes = expHoles, "wrong number of vectors outside R + R");
  Print("exactly ", expHoles,
        " vectors outside R + R, all at distance 3\n");
  Print("degree ", q, ": Saxl diameter exactly 3, all checks passed\n");
end;;
