AbortRun := function(message)
  Print("error ", message, "\n");
  QUIT_GAP(1);
end;;

if LoadPackage("images") = fail then
  AbortRun("the GAP package Images is required");
fi;

# The candidate x = v + omega*w is regular for the full scalar group when
# w has trivial stabiliser in the signed M24 complement.  The C++ step has
# already distinguished <v> from the other three GF(3)-lines in <v,w> by a
# 2.Co1-invariant zero count.  Consequently an element taking one candidate
# to a scalar multiple of another must use a GF(3)-scalar and lie in M24.
# Thus exact M24 stabilisers and exact M24 canonical images are sufficient.

if not IsBound(GAPInfo.SystemEnvironment.CO1_F9_DIR) then
  AbortRun("CO1_F9_DIR is not set");
fi;
directory := GAPInfo.SystemEnvironment.CO1_F9_DIR;;
candidate_file := GAPInfo.SystemEnvironment.CO1_F9_CANDIDATES;;
required_orbits := 267;;

Read(Concatenation(directory, "/m24_action.g"));
M24 := Group(M24_SIGNED_GENERATORS);;
if Size(M24) <> 244823040 then
  AbortRun("the signed permutation group does not have order |M24|");
fi;

Antipode := function(point)
  if point <= 24 then
    return point + 24;
  fi;
  return point - 24;
end;;

SignedSupport := function(vector)
  local support, i;
  support := [];
  for i in [1..24] do
    if vector[i] = 1 then
      Add(support, i);
    elif vector[i] = 2 then
      Add(support, i + 24);
    fi;
  od;
  return Set(support);
end;;

fixed_support := SignedSupport(M24_FIXED_VECTOR);;
if Length(fixed_support) <> 24 then
  AbortRun("the fixed vector should have full support");
fi;
if not ForAll(M24_SIGNED_GENERATORS,
    generator -> OnSets(fixed_support, generator) = fixed_support) then
  AbortRun("the signed generators do not fix the chosen vector");
fi;
if not ForAll(M24_SIGNED_GENERATORS,
    generator -> ForAll([1..48],
      point -> Antipode(point^generator) = Antipode(point)^generator)) then
  AbortRun("a signed generator does not preserve antipodal pairs");
fi;

lines := SplitString(StringFile(candidate_file), "\n", "\r");;
if Length(lines) < 2 or lines[1] <> "vector" then
  AbortRun("bad candidate input");
fi;

representatives := [];;
examined := 0;;
nonregular := 0;;
equivalent := 0;;
start_time := Runtime();;

for line in lines{[2..Length(lines)]} do
  if line = "" then
    continue;
  fi;
  examined := examined + 1;
  vector := List(SplitString(line, ","), Int);;
  if Length(vector) <> 24 or not ForAll(vector, x -> x in [0,1,2]) then
    AbortRun("a candidate is not a vector in GF(3)^24");
  fi;

  support := SignedSupport(vector);;
  stabiliser := Stabilizer(M24, support, OnSets);;
  if Size(stabiliser) <> 1 then
    nonregular := nonregular + 1;
    continue;
  fi;

  transporter := CanonicalImagePerm(
      M24, support, OnSets, rec(stabilizer := stabiliser));;
  if not transporter in M24 then
    AbortRun("a canonical-image transporter left M24");
  fi;
  canonical_support := OnSets(support, transporter);;
  if canonical_support in representatives then
    equivalent := equivalent + 1;
    continue;
  fi;

  Add(representatives, canonical_support);
  if Length(representatives) mod 25 = 0 then
    Print("regular_orbits_found ", Length(representatives),
          " candidates_examined ", examined,
          " elapsed_seconds ", QuoInt(Runtime() - start_time, 1000), "\n");
  fi;
  if Length(representatives) = required_orbits then
    break;
  fi;
od;

if Length(representatives) <> required_orbits then
  AbortRun(Concatenation("only ", String(Length(representatives)),
                         " regular orbits were found"));
fi;

# The group generated by 2.Co1 and all scalars in GF(9) has order 4|2.Co1|:
# its intersection with the scalar group is the central group of order two.
co1_cover_order := 8315553613086720000;;
full_scalar_group_order := 4 * co1_cover_order;;
projective_threshold := 9^23 - 1;;
regular_vectors := required_orbits * full_scalar_group_order;;
margin := regular_vectors - projective_threshold;;
if margin <= 0 then
  AbortRun("the projective density inequality is not strict");
fi;

Print("candidates_examined ", examined, "\n");
Print("nontrivial_stabiliser ", nonregular, "\n");
Print("equivalent_to_earlier_orbit ", equivalent, "\n");
Print("regular_orbits ", required_orbits, "\n");
Print("full_scalar_group_order ", full_scalar_group_order, "\n");
Print("regular_vectors ", regular_vectors, "\n");
Print("projective_threshold ", projective_threshold, "\n");
Print("strict_margin ", margin, "\n");
Print("regular_plus_regular_is_whole_space true\n");

QUIT;
