# The affine seed (Lemma 3.1 of the paper).
#
# L0 = D:P <= GL(9,3) is the monomial group of order 1152 whose coordinates
# are indexed by a 3x3 grid: D consists of the diagonal sign matrices whose
# sign pattern has all row and column sums zero, and P = (S3 x S3):C2
# permutes rows and columns and transposes the grid.
#
# The script checks that L0 acts irreducibly on U0 = GF(3)^9 with exactly
# two regular orbits, that O + O + O = U0 for each regular orbit O, and
# that the all-ones vector lies in O_a + O_b for exactly one ordered pair
# (a, b) of regular orbits, which is diagonal.

Require := function(condition, message)
  if not condition then
    Error(message);
  fi;
end;;

F := GF(3);;
pos := function(i, j) return 3*(i-1) + j; end;;

# D: generated by the four 2x2 plus-square sign patterns.
Dgens := [];;
for i in [1, 2] do
  for j in [1, 2] do
    d := IdentityMat(9, F);
    for c in [pos(i, j), pos(i, j+1), pos(i+1, j), pos(i+1, j+1)] do
      d[c][c] := -One(F);
    od;
    Add(Dgens, d);
  od;
od;

# P: row cycle, row swap and transpose, as permutations of the nine cells.
gridperm := function(f)
  local imgs, i, j, t;
  imgs := [];
  for i in [1..3] do
    for j in [1..3] do
      t := f(i, j);
      imgs[pos(i, j)] := pos(t[1], t[2]);
    od;
  od;
  return PermList(imgs);
end;;

rho   := gridperm(function(i, j) return [i mod 3 + 1, j]; end);;
sigma := gridperm(function(i, j)
           if i = 1 then return [2, j];
           elif i = 2 then return [1, j];
           else return [i, j]; fi; end);;
tau   := gridperm(function(i, j) return [j, i]; end);;

Pgens := List([rho, sigma, tau], p -> PermutationMat(p, 9, F));;
L := Group(Concatenation(Dgens, Pgens));;
Require(Size(L) = 1152, "L0 should have order 1152");
Print("group of order 1152 constructed\n");

Require(MTX.IsIrreducible(GModuleByMats(GeneratorsOfGroup(L), F)),
        "L0 should act irreducibly on GF(3)^9");
Print("irreducibility verified\n");

vecs := AsSSortedList(F^9);;
orbs := OrbitsDomain(L, vecs);;
reg := Filtered(orbs, o -> Length(o) = 1152);;
Require(Length(reg) = 2, "there should be exactly two regular orbits");
Print("exactly two regular orbits found\n");

num := v -> NumberFFVector(v, 3) + 1;;

# (i): O + O + O = U0 for each regular orbit O.
B2 := fail;;
for O in reg do
  B2 := BlistList([1..3^9], []);
  for x in O do
    for y in O do
      B2[num(x + y)] := true;
    od;
  od;
  for t in vecs do
    if not ForAny(O, x -> B2[num(t - x)]) then
      Error("(i) fails: a vector is not a sum of three elements of O");
    fi;
  od;
od;
Print("(i) verified: O + O + O = U0 for both regular orbits\n");

# (ii): the all-ones vector lies in O_a + O_b for exactly one pair (a, b).
one := Sum(IdentityMat(9, F));;
Osets := List(reg, Set);;
pairs := [];;
for i in [1, 2] do
  for j in [1, 2] do
    if ForAny(reg[i], x -> (one - x) in Osets[j]) then
      Add(pairs, [i, j]);
    fi;
  od;
od;
Require(Length(pairs) = 1 and pairs[1][1] = pairs[1][2],
        "(ii) fails: the all-ones vector should lie in O_a + O_b for exactly one, diagonal, pair");
Print("(ii) verified: the unique pair is diagonal\n");

Print("affine seed: all checks passed\n");
QUIT;
