# The affine input (Lemma 3.3 of the paper).
#
# L0 = D:P <= GL(9,3) is the monomial group of order 1152 whose coordinates
# are indexed by a 3x3 grid.  The group D is generated by sign changes on
# 2x2 subgrids, and P = (S3 x S3):C2 permutes rows and columns and transposes
# the grid.
#
# The script checks that L0 acts irreducibly on U0 = GF(3)^9 with exactly
# two regular orbits O0,O1 with the displayed representatives, that
# O + O + O = U0 for each regular orbit O, and that the all-ones vector
# lies in O_a + O_b if and only if a = b = 0.

Require := function(condition, message)
  if not condition then
    Error(message);
  fi;
end;;

F := GF(3);;
pos := function(i, j) return 3*(i-1) + j; end;;

# D: generated by the four 2x2 plus-square sign patterns.
Dgens := [];;
for i in [1, 2] do
  for j in [1, 2] do
    d := IdentityMat(9, F);
    for c in [pos(i, j), pos(i, j+1), pos(i+1, j), pos(i+1, j+1)] do
      d[c][c] := -One(F);
    od;
    Add(Dgens, d);
  od;
od;
D := Group(Dgens);;
Require(Size(D) = 16, "D should have order 16");
for rows in Combinations([1..3], 2) do
  for cols in Combinations([1..3], 2) do
    d := IdentityMat(9, F);
    for i in rows do
      for j in cols do
        d[pos(i, j)][pos(i, j)] := -One(F);
      od;
    od;
    Require(d in D, "the four adjacent blocks should generate every 2x2 sign change");
  od;
od;

# P: row cycle, row swap and transpose, as permutations of the nine cells.
gridperm := function(f)
  local imgs, i, j, t;
  imgs := [];
  for i in [1..3] do
    for j in [1..3] do
      t := f(i, j);
      imgs[pos(i, j)] := pos(t[1], t[2]);
    od;
  od;
  return PermList(imgs);
end;;

rho   := gridperm(function(i, j) return [i mod 3 + 1, j]; end);;
sigma := gridperm(function(i, j)
           if i = 1 then return [2, j];
           elif i = 2 then return [1, j];
           else return [i, j]; fi; end);;
tau   := gridperm(function(i, j) return [j, i]; end);;

Pgens := List([rho, sigma, tau], p -> PermutationMat(p, 9, F));;
L := Group(Concatenation(Dgens, Pgens));;
Require(Size(L) = 1152, "L0 should have order 1152");
Print("group of order 1152 constructed\n");

Require(MTX.IsIrreducible(GModuleByMats(GeneratorsOfGroup(L), F)),
        "L0 should act irreducibly on GF(3)^9");
Print("irreducibility verified\n");

vecs := AsSSortedList(F^9);;
orbs := OrbitsDomain(L, vecs);;
reg := Filtered(orbs, o -> Length(o) = 1152);;
Require(Length(reg) = 2, "there should be exactly two regular orbits");

# Fix the labelling used in Lemma 3.3.
u0 := List([0, 1, -1, 1, 0, 1, 1, 1, 1], x -> x*One(F));;
u1 := List([0, 0, -1, 0, 1, 1, 1, 1, 1], x -> x*One(F));;
O0 := Orbit(L, u0, OnRight);;
O1 := Orbit(L, u1, OnRight);;
Require(Size(Stabilizer(L, u0, OnRight)) = 1 and
        Size(Stabilizer(L, u1, OnRight)) = 1,
        "the displayed representatives should have trivial stabilisers");
Require(ForAll(reg, O -> Set(O) = Set(O0) or Set(O) = Set(O1)),
        "the displayed representatives should label the two regular orbits");
reg := [O0, O1];;
Print("exactly two regular orbits found and labelled by u0,u1\n");

num := v -> NumberFFVector(v, 3) + 1;;

# (i): O + O + O = U0 for each regular orbit O.
B2 := fail;;
for O in reg do
  B2 := BlistList([1..3^9], []);
  for x in O do
    for y in O do
      B2[num(x + y)] := true;
    od;
  od;
  for t in vecs do
    if not ForAny(O, x -> B2[num(t - x)]) then
      Error("(i) fails: a vector is not a sum of three elements of O");
    fi;
  od;
od;
Print("(i) verified: O + O + O = U0 for both regular orbits\n");

# (ii): the all-ones vector lies in O_a + O_b for exactly one pair (a, b).
one := Sum(IdentityMat(9, F));;
Osets := List(reg, Set);;
pairs := [];;
for i in [1, 2] do
  for j in [1, 2] do
    if ForAny(reg[i], x -> (one - x) in Osets[j]) then
      Add(pairs, [i, j]);
    fi;
  od;
od;
Require(pairs = [[1, 1]],
        "(ii) fails: the all-ones vector should lie only in O0 + O0");
Print("(ii) verified: the all-ones vector lies only in O0 + O0\n");

Print("affine input: all checks passed\n");
QUIT;
